# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# Site settings
locale: en-US
title: Ivan's Notes
title_separator: "|"
# subtitle:
name: Ivan Huang
description: "Ivan Huang (ivanhjc)'s personal blog/notebook dealing with topics majorly focusing on programming, math, music etc."
url: https://notes.ivanhjc.net
# baseurl: /ivans-notes
# repository: ivanhjc/ivans-notes
# teaser:
# logo:
# masthead_title:
# breadcrumbs: true
words_per_minute: 200

comments:
  provider: disqus
  disqus:
    shortname: ivansnotes
    
# reCaptcha:
  # siteKey:
  # secret:
  
search: true
search_full_content: true
# search_provider: algolia
# algolia:
#   application_id         : QB6HVGBSBA # YOUR_APPLICATION_ID
#   index_name             : minimal_mistakes # YOUR_INDEX_NAME
#   search_only_api_key    : 9d5014e5bbc77372547bce778dfa5663 # YOUR_SEARCH_ONLY_API_KEY
#   powered_by             : true # true (default), false
#   files_to_exclude:
#     - _posts/2017-11-28-post-exclude-search.md
# SEO Related
# google_site_verification :
# bing_site_verification   :
# yandex_site_verification :
# naver_site_verification  :

twitter:
  username: ivanhjc_
# og_image: 

social:
  type: Person
  name: Ivan Huang
  links:
    - "https://twitter.com/ivanhjc_"

# Analytics
analytics:
  provider: google-gtag
  google:
    tracking_id: UA-143784270-1
    anonymize_ip: false

author:
  name: Ivan Huang
  avatar: https://res.cloudinary.com/ivanhjc/image/upload/v1602736588/lADPBG1Q53OmyVjNCmzNCmw_2668_2668_rxbufo.jpg
  bio: "Intrigued by intriguing things"
  location: Shenzhen, China
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://ivanhjc.net"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ivanhjc_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ivanhjc"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://ivanhjc.net"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ivanhjc_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ivanhjc"
      
include:
  - _pages
  - _demo
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: Asia/Shanghai
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

